package com.sitool.servicedesk.incident.service;

import com.sitool.servicedesk.category.entity.Category;
import com.sitool.servicedesk.category.exceptions.CategoryNotFoundException;
import com.sitool.servicedesk.category.repository.CategoryRepository;
import com.sitool.servicedesk.ci.entity.CI;
import com.sitool.servicedesk.ci.exceptions.CINotFoundException;
import com.sitool.servicedesk.ci.repository.CIRepository;
import com.sitool.servicedesk.group.entity.Group;
import com.sitool.servicedesk.group.exceptions.GroupNotFoundException;
import com.sitool.servicedesk.group.repository.GroupRepository;
import com.sitool.servicedesk.incident.dto.request.CreateIncidentRequest;
import com.sitool.servicedesk.incident.dto.request.UpdateIncidentRequest;
import com.sitool.servicedesk.incident.dto.response.IncidentDto;
import com.sitool.servicedesk.incident.dto.response.NextIncidentNumberResponse;
import com.sitool.servicedesk.incident.entity.Incident;
import com.sitool.servicedesk.incident.exceptions.IncidentAlreadyExistException;
import com.sitool.servicedesk.incident.exceptions.IncidentNotFoundException;
import com.sitool.servicedesk.incident.mapper.IncidentMapper;
import com.sitool.servicedesk.incident.repository.IncidentRepository;
import com.sitool.servicedesk.shared.utils.PriorityCalculator;
import com.sitool.servicedesk.status.entity.Status;
import com.sitool.servicedesk.status.exceptions.StatusNotFoundException;
import com.sitool.servicedesk.status.repository.StatusRepository;
import com.sitool.servicedesk.sybcategory.entity.Subcategory;
import com.sitool.servicedesk.sybcategory.exceptions.SubcategoryNotFoundException;
import com.sitool.servicedesk.sybcategory.repository.SubcategoryRepository;
import com.sitool.servicedesk.user.entity.User;
import com.sitool.servicedesk.user.exceptions.UserNotFoundException;
import com.sitool.servicedesk.user.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Implementation of {@link IncidentService} for managing incidents.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class IncidentServiceImpl implements IncidentService {

    private final IncidentRepository incidentRepository;
    private final UserRepository userRepository;
    private final CategoryRepository categoryRepository;
    private final SubcategoryRepository subcategoryRepository;
    private final StatusRepository statusRepository;
    private final CIRepository ciRepository;
    private final GroupRepository groupRepository;
    private final IncidentMapper mapper;

    /**
     * Returns the next available incident number generated by the database sequence.
     *
     * <p>The number is formatted as INC followed by a zero-padded sequence value,
     * for example INC0000001.</p>
     *
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public NextIncidentNumberResponse getNextIncidentNumber() {
        Long number = incidentRepository.getNextNumber();
        return new NextIncidentNumberResponse("INC" + String.format("%07d", number));
    }

    /**
     * Creates a new incident.
     *
     * <p>Validates all referenced entities before saving.
     * Priority is calculated automatically based on impact and urgency.</p>
     *
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public IncidentDto createIncident(CreateIncidentRequest request) {

        if (incidentRepository.existsByNumber(request.number())) {
            log.error("createIncident: incident number already exists {}",  request.number());
            throw new IncidentAlreadyExistException();
        }

        Incident newIncident = new Incident();
        newIncident.setNumber(request.number());

        User requester = userRepository.findById(request.requesterId()).orElseThrow(() -> {
            log.info("createIncident: requester did not founded by id {}", request.requesterId());
            return new UserNotFoundException();
        });
        newIncident.setRequester(requester);

        Category category = categoryRepository.findById(request.categoryId()).orElseThrow(() -> {
            log.info("createIncident: category not found id {}", request.categoryId());
            return new CategoryNotFoundException();
        });
        newIncident.setCategory(category);

        if (request.subcategoryId() != null) {
            Subcategory subcategory = subcategoryRepository.findById(request.subcategoryId()).orElseThrow(() -> {
                log.info("createIncident: subcategory not found id {}", request.subcategoryId());
                return new SubcategoryNotFoundException();
            });
            newIncident.setSubcategory(subcategory);
        }

        Status status = statusRepository.findById(request.statusId()).orElseThrow(() -> {
            log.info("createIncident: status not found id {}", request.statusId());
            return new StatusNotFoundException();
        });

        newIncident.setStatus(status);

        newIncident.setImpact(request.impact());
        newIncident.setUrgency(request.urgency());
        newIncident.setPriority(PriorityCalculator.calculate(request.impact(), request.urgency()));


        if (request.ciId() != null) {
            CI ci = ciRepository.findById(request.ciId()).orElseThrow(() -> {
                log.info("createIncident: ci not found id {}",request.ciId());
                return new CINotFoundException();
            });
            newIncident.setCi(ci);
        }

        if (request.groupId() != null) {
            Group group = groupRepository.findById(request.groupId()).orElseThrow(() -> {
                log.info("createIncident: group not found id {}", request.groupId());
                return new GroupNotFoundException();
            });
            newIncident.setGroup(group);
        }

        if (request.assigneeId() != null) {
            User assignee = userRepository.findById(request.assigneeId()).orElseThrow(() -> {
                log.info("createIncident: assignee not found id {}", request.assigneeId());
                return new UserNotFoundException();
            });
            newIncident.setAssignee(assignee);
        }

        newIncident.setShortDescription(request.shortDescription());
        newIncident.setDescription(request.description());

        incidentRepository.save(newIncident);

        return mapper.toIncidentDto(newIncident);
    }

    /**
     * Updates an existing incident.
     *
     * <p>Only modified fields are persisted to avoid unnecessary database calls.
     * Priority is recalculated automatically if impact or urgency changes.</p>
     *
     * {@inheritDoc}
     */
    @Override
    @Transactional
    public IncidentDto updateIncident(UUID incidentId, UpdateIncidentRequest request) {
        boolean updated = false;

        Incident currentIncident = incidentRepository.findById(incidentId).orElseThrow(() -> {
            log.info("updateIncident: incident not found id {}", incidentId);
            return new IncidentNotFoundException();
        });

        if (!currentIncident.getRequester().getId().equals(request.requesterId())) {
            User newRequester = userRepository.findById(request.requesterId()).orElseThrow(() -> {
                log.info("updateIncident: requester not found id {}", request.requesterId());
                return new UserNotFoundException();
            });
            currentIncident.setRequester(newRequester);
            updated = true;
        }

        if (!currentIncident.getCategory().getId().equals(request.categoryId())) {
            Category newCategory = categoryRepository.findById(request.categoryId()).orElseThrow(() -> {
                log.info("updateIncident: category not found id {}", request.categoryId());
                return new CategoryNotFoundException();
            });
            currentIncident.setCategory(newCategory);
            updated = true;
        }

        if (request.subcategoryId() != null &&
                !request.subcategoryId().equals(currentIncident.getSubcategory() != null ? currentIncident.getSubcategory().getId() : null)) {
            Subcategory newSubcategory = subcategoryRepository.findById(request.subcategoryId()).orElseThrow(() -> {
                log.info("updateIncident: subcategory not found id {}", request.subcategoryId());
                return new SubcategoryNotFoundException();
            });
            currentIncident.setSubcategory(newSubcategory);
            updated = true;
        }

        if (!currentIncident.getStatus().getId().equals(request.statusId())) {
            Status newStatus = statusRepository.findById(request.statusId()).orElseThrow(() -> {
                log.info("updateIncident: status not found id {}", request.statusId());
                return new StatusNotFoundException();
            });
            currentIncident.setStatus(newStatus);
            updated = true;
        }

        if (currentIncident.getImpact() != request.impact() || currentIncident.getUrgency() != request.urgency()) {
            currentIncident.setImpact(request.impact());
            currentIncident.setUrgency(request.urgency());
            currentIncident.setPriority(PriorityCalculator.calculate(request.impact(), request.urgency()));
            updated = true;
        }

        if (request.ciId() != null && !request.ciId().equals(currentIncident.getCi() != null ? currentIncident.getCi().getId() : null)) {
            CI newCi = ciRepository.findById(request.ciId()).orElseThrow(() -> {
                log.info("updateIncident: ci not found id {}", request.ciId());
                return new CINotFoundException();
            });
            currentIncident.setCi(newCi);
            updated = true;
        }

        if (request.groupId() != null && !request.groupId().equals(currentIncident.getGroup() != null ? currentIncident.getGroup().getId() : null)) {
            Group newGroup = groupRepository.findById(request.groupId()).orElseThrow(() -> {
                log.info("updateIncident: group not found id {}", request.groupId());
                return new GroupNotFoundException();
            });
            currentIncident.setGroup(newGroup);
            updated = true;
        }

        if (request.assigneeId() != null && !request.assigneeId().equals(currentIncident.getAssignee() != null ? currentIncident.getAssignee().getId() : null)) {
            User newAssignee = userRepository.findById(request.assigneeId()).orElseThrow(() -> {
                log.info("updateIncident: assignee not found id {}", request.assigneeId());
                return new UserNotFoundException();
            });
            currentIncident.setAssignee(newAssignee);
            updated = true;
        }

        if (!currentIncident.getShortDescription().equals(request.shortDescription())) {
            currentIncident.setShortDescription(request.shortDescription());
            updated = true;
        }

        if (!Objects.equals(currentIncident.getDescription(), request.description())) {
            currentIncident.setDescription(request.description());
            updated = true;
        }

        if (updated) {
            incidentRepository.save(currentIncident);
        }

        return mapper.toIncidentDto(currentIncident);
    }

    /**
     * Returns an incident by its ID.
     * {@inheritDoc}
     */
    @Override
    @Transactional(readOnly = true)
    public IncidentDto getIncident(UUID incidentId) {
        Incident currentIncident = incidentRepository.findById(incidentId).orElseThrow(() -> {
            log.info("getIncident: incident not found id {}", incidentId);
            return new IncidentNotFoundException();
        });
        return mapper.toIncidentDto(currentIncident);
    }

    /**
     * Returns all incidents.
     * {@inheritDoc}
     */
    @Override
    @Transactional(readOnly = true)
    public List<IncidentDto> getAllIncidents() {
        return incidentRepository.findAll()
                .stream()
                .map(mapper::toIncidentDto)
                .toList();
    }
}
