package com.sitool.servicedesk.incident.service;

import com.sitool.servicedesk.incident.dto.request.CreateIncidentRequest;
import com.sitool.servicedesk.incident.dto.request.UpdateIncidentRequest;
import com.sitool.servicedesk.incident.dto.response.IncidentDto;
import com.sitool.servicedesk.incident.dto.response.NextIncidentNumberResponse;
import com.sitool.servicedesk.incident.exceptions.IncidentNotFoundException;
import com.sitool.servicedesk.incident.exceptions.IncidentAlreadyExistException;

import java.util.List;
import java.util.UUID;

/**
 * Service interface for managing incidents.
 *
 * <p>Provides operations for creating, updating, and retrieving incidents
 * within the service desk system.</p>
 */
public interface IncidentService {

    /**
     * Returns the next available incident number generated by the database sequence.
     *
     * <p>The number is formatted as INC followed by a zero-padded sequence value,
     * for example INC0000001. The number is reserved for display on the form
     * before the incident is saved.</p>
     *
     * @return the next incident number as a formatted string
     */
    NextIncidentNumberResponse getNextIncidentNumber();

    /**
     * Creates a new incident.
     *
     * @param request the request containing incident data
     * @return the created incident
     * @throws IncidentAlreadyExistException if an incident with the same number already exists
     */
    IncidentDto createIncident(CreateIncidentRequest request);

    /**
     * Updates an existing incident.
     *
     * @param incidentId the UUID of the incident to update
     * @param request    the request containing updated incident data
     * @return the updated incident
     * @throws IncidentNotFoundException if no incident with the given ID exists
     */
    IncidentDto updateIncident(UUID incidentId, UpdateIncidentRequest request);

    /**
     * Returns an incident by its ID.
     *
     * @param incidentId the UUID of the incident to retrieve
     * @return the incident data
     * @throws IncidentNotFoundException if no incident with the given ID exists
     */
    IncidentDto getIncident(UUID incidentId);

    /**
     * Returns a list of all incidents.
     *
     * @return list of all incidents
     */
    List<IncidentDto> getAllIncidents();
}
