databaseChangeLog:
  - changeSet:
      id: 3
      author: sitool
      changes:
        - createTable:
            tableName: configuration_items
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: TEXT
                  constraints:
                    nullable: true
              - column:
                  name: type
                  type: VARCHAR(150)
                  constraints:
                    nullable: true
              - column:
                  name: manufacturer
                  type: VARCHAR(150)
                  constraints:
                    nullable: true
              - column:
                  name: serial_number
                  type: VARCHAR(150)
                  constraints:
                    nullable: true
              - column:
                  name: model
                  type: VARCHAR(150)
                  constraints:
                    nullable: true
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false