package com.sitool.servicedesk.incident.controller;

import com.sitool.servicedesk.exceptions.handling.response.ValidationErrorDto;
import com.sitool.servicedesk.incident.dto.request.CreateIncidentRequest;
import com.sitool.servicedesk.incident.dto.request.UpdateIncidentRequest;
import com.sitool.servicedesk.incident.dto.response.IncidentDto;
import com.sitool.servicedesk.incident.dto.response.NextIncidentNumberResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

/**
 * API contract for incident-related operations.
 */
@Tag(name = "Incidents", description = "Operations related to incident")
@RequestMapping("/api/v1/incidents")
public interface IncidentApi {

    @Operation(
            summary = "Get next incident number",
            description = "Returns the next available incident number generated by the database sequence."
    )
    @ApiResponse(
            responseCode = "200",
            description = "Next incident number retrieved successfully",
            content = @Content(
                    mediaType = "application/json",
                    examples = @ExampleObject(value = "\"INC0000001\"")
            )
    )
    @GetMapping("/next-number")
    NextIncidentNumberResponse getNextIncidentNumber();

    @Operation(summary = "Register new incident", description = "Creates a new incident record.")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Incident created successfully",
                    content = @Content(mediaType = "application/json",
                            schema = @Schema(implementation = IncidentDto.class),
                            examples = @ExampleObject(value = """
                                    {
                                      "id": "767ea865-8b32-454c-af05-52508be4033c",
                                      "number": "INC0000001",
                                      "requesterId": "550e8400-e29b-41d4-a716-446655440000",
                                      "categoryId": "550e8400-e29b-41d4-a716-446655440001",
                                      "subcategoryId": "550e8400-e29b-41d4-a716-446655440002",
                                      "statusId": "550e8400-e29b-41d4-a716-446655440003",
                                      "priority": "HIGH",
                                      "impact": "HIGH",
                                      "urgency": "HIGH",
                                      "ciId": "550e8400-e29b-41d4-a716-446655440004",
                                      "groupId": "550e8400-e29b-41d4-a716-446655440005",
                                      "assigneeId": "550e8400-e29b-41d4-a716-446655440006",
                                      "shortDescription": "Cannot connect to VPN",
                                      "description": "User is unable to connect to corporate VPN since this morning",
                                      "servicenowNumber": null,
                                      "servicenowSynced": false,
                                      "servicenowSyncedAt": null
                                    }
                                    """))
            ),
            @ApiResponse(
                    responseCode = "409",
                    description = "Incident already exists"
            ),
            @ApiResponse(responseCode = "400", description = "Invalid request payload",
                    content = @Content(mediaType = "application/json",
                            array = @ArraySchema(schema = @Schema(implementation = ValidationErrorDto.class)),
                            examples = @ExampleObject(value = """
                                    [
                                      { "field": "name",
                                        "message": "must be a well-formed name" },
                                      { "field": "name",
                                        "message": "must not be blank" }
                                    ]
                                    """))
            )
    })
    @ResponseStatus(HttpStatus.CREATED)
    @PostMapping
    IncidentDto createIncident(@Valid @RequestBody CreateIncidentRequest request);

    @Operation(
            summary = "Update incident",
            description = "Updates editable information for the specified incident."
    )
    @ApiResponses(value = {
            @ApiResponse(
                    responseCode = "200",
                    description = "Incident updated successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = IncidentDto.class)
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid request data or UUID format"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Incident not found"
            )
    })
    @PutMapping("/{incidentId}")
    IncidentDto updateIncident(@PathVariable UUID incidentId, @Valid @RequestBody UpdateIncidentRequest request);

    @Operation(
            summary = "Get incident by id",
            description = "Returns incident information for the specified incidentId (UUID)."
    )
    @ApiResponses(value = {
            @ApiResponse(
                    responseCode = "200",
                    description = "Incident retrieved successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = IncidentDto.class)
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid UUID format"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "Incident not found"
            )
    })
    @GetMapping("/{incidentId}")
    IncidentDto getIncident(@PathVariable UUID incidentId);

    @Operation(
            summary = "Get all incidents",
            description = "Returns a list of all incidents."
    )
    @ApiResponse(
            responseCode = "200",
            description = "Incidents retrieved successfully",
            content = @Content(
                    mediaType = "application/json",
                    array = @ArraySchema(schema = @Schema(implementation = IncidentDto.class))
            )
    )
    @GetMapping
    List<IncidentDto> getAllIncidents();
}
